# Generated by Django 6.0.1 on 2026-01-27 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название курса')),
                ('slug', models.SlugField(help_text='Например: geometry-9-class', unique=True, verbose_name='URL-адрес')),
                ('short_description', models.TextField(max_length=300, verbose_name='Краткое описание')),
                ('full_description', models.TextField(blank=True, verbose_name='Подробное описание')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='courses/covers/', verbose_name='Обложка курса')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активен')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок отображения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название урока')),
                ('lesson_type', models.CharField(choices=[('video', 'Видеоурок'), ('text', 'Текстовый урок'), ('hybrid', 'Гибридный (видео + текст)'), ('practice', 'Практическое занятие')], default='hybrid', max_length=20, verbose_name='Тип урока')),
                ('content', models.TextField(blank=True, verbose_name='Теоретический материал (текст)')),
                ('video_url', models.URLField(blank=True, verbose_name='Ссылка на видео (YouTube/Vimeo)')),
                ('duration', models.IntegerField(default=0, help_text='Для видеоуроков', verbose_name='Длительность (минут)')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок в модуле')),
                ('is_free', models.BooleanField(default=False, verbose_name='Бесплатный урок')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название задания')),
                ('description', models.TextField(verbose_name='Описание задания')),
                ('assignment_type', models.CharField(choices=[('test', 'Тест с выбором ответа'), ('text_input', 'Текстовый ответ'), ('file_upload', 'Загрузка файла'), ('code', 'Написание кода/формулы')], default='test', max_length=20, verbose_name='Тип задания')),
                ('points', models.IntegerField(default=1, verbose_name='Баллы за задание')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок в уроке')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='users.lesson')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название модуля')),
                ('description', models.TextField(blank=True, verbose_name='Описание модуля')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок в курсе')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='users.course')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='users.module'),
        ),
        migrations.CreateModel(
            name='TestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='Текст вопроса')),
                ('question_type', models.CharField(choices=[('single_choice', 'Один правильный ответ'), ('multiple_choice', 'Несколько правильных ответов'), ('true_false', 'Верно/Неверно')], default='single_choice', max_length=20, verbose_name='Тип вопроса')),
                ('explanation', models.TextField(blank=True, help_text='Показывается после ответа', verbose_name='Объяснение ответа')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок в задании')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='users.assignment')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AnswerOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Текст ответа')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Правильный ответ')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок отображения')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='users.testquestion')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
