# Generated by Django 6.0.1 on 2026-01-27 02:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_course_lesson_assignment_module_lesson_module_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название категории')),
                ('slug', models.SlugField(unique=True, verbose_name='URL-адрес')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('icon', models.CharField(default='📚', help_text='Эмодзи или название класса иконки', max_length=50, verbose_name='Иконка')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок отображения')),
            ],
            options={
                'verbose_name': 'Категория материалов',
                'verbose_name_plural': 'Категории материалов',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название материала')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('file', models.FileField(blank=True, null=True, upload_to='materials/files/', verbose_name='Файл')),
                ('external_url', models.URLField(blank=True, help_text='Если материал расположен на другом сайте', verbose_name='Внешняя ссылка')),
                ('material_type', models.CharField(choices=[('pdf', 'PDF документ'), ('video', 'Видео'), ('article', 'Статья'), ('presentation', 'Презентация'), ('other', 'Другое')], default='pdf', max_length=20, verbose_name='Тип материала')),
                ('is_free', models.BooleanField(default=False, verbose_name='Бесплатный')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок в категории')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='users.materialcategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Методический материал',
                'verbose_name_plural': 'Методические материалы',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата записи')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('progress', models.IntegerField(default=0, help_text='Процент прохождения курса', verbose_name='Прогресс (%)')),
                ('last_accessed', models.DateTimeField(auto_now=True, verbose_name='Последний доступ')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='users.course')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Запись на курс',
                'verbose_name_plural': 'Записи на курсы',
                'unique_together': {('student', 'course')},
            },
        ),
    ]
