# Generated by Django 6.0.1 on 2026-01-27 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_materialcategory_material_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='page_count',
            field=models.IntegerField(blank=True, default=0, verbose_name='Количество страниц'),
        ),
        migrations.AddField(
            model_name='material',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='materials/thumbnails/', verbose_name='Миниатюра'),
        ),
    ]
