# Generated by Django 6.0.1 on 2026-01-28 20:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_material_page_count_material_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.IntegerField(verbose_name='Номер страницы')),
                ('annotation_type', models.CharField(choices=[('highlight', 'Выделение текста'), ('note', 'Текстовая заметка'), ('drawing', 'Рисунок или пометка')], default='highlight', max_length=20, verbose_name='Тип аннотации')),
                ('content', models.JSONField(default=dict, verbose_name='Содержание аннотации')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='users.material', verbose_name='Материал')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_annotations', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Аннотация в PDF',
                'verbose_name_plural': 'Аннотации в PDF',
                'ordering': ['material', 'page_number', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='PDFBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.IntegerField(verbose_name='Номер страницы')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('comment', models.TextField(blank=True, help_text='Необязательная заметка к закладке', null=True, verbose_name='Комментарий')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='users.material', verbose_name='Материал')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_bookmarks', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Закладка в PDF',
                'verbose_name_plural': 'Закладки в PDF',
                'ordering': ['material', 'page_number'],
                'unique_together': {('user', 'material', 'page_number')},
            },
        ),
    ]
