# Generated by Django 6.0.1 on 2026-01-29 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_pdfannotation_pdfbookmark'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemGenerator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название генератора')),
                ('generator_type', models.CharField(choices=[('python_function', 'Python функция'), ('template_based', 'Шаблон с подстановкой')], default='python_function', max_length=20, verbose_name='Тип генератора')),
                ('python_code', models.TextField(blank=True, help_text='Функция должна возвращать словарь с параметрами задачи', verbose_name='Код Python генератора')),
                ('template_text', models.TextField(blank=True, verbose_name='Шаблон задачи')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='Конфигурация')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
            ],
            options={
                'verbose_name': 'Генератор задач',
                'verbose_name_plural': 'Генераторы задач',
            },
        ),
        migrations.AddField(
            model_name='assignment',
            name='answer_type',
            field=models.CharField(choices=[('single_choice', 'Выбор ответа 1-4'), ('decimal_input', 'Ввод десятичной дроби'), ('text_input', 'Текстовый ответ')], default='decimal_input', max_length=20, verbose_name='Тип ответа'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='required_correct',
            field=models.IntegerField(default=10, help_text='Сколько задач нужно решить правильно для прохождения', verbose_name='Требуется правильных решений'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='assignment_type',
            field=models.CharField(choices=[('test', 'Тест'), ('text_input', 'Текстовый ответ'), ('file_upload', 'Загрузка файла'), ('code', 'Код')], default='test', max_length=20, verbose_name='Тип задания'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='users.lesson', verbose_name='Урок'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='points',
            field=models.IntegerField(default=1, verbose_name='Баллы'),
        ),
        migrations.CreateModel(
            name='GeneratedProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_data', models.JSONField(default=dict, help_text='JSON с параметрами сгенерированной задачи', verbose_name='Данные задачи')),
                ('condition_text', models.TextField(blank=True, help_text='Человекочитаемый текст условия задачи', verbose_name='Текст условия')),
                ('correct_answer', models.JSONField(help_text='Правильный ответ в формате JSON', verbose_name='Правильный ответ')),
                ('attempts_count', models.IntegerField(default=0, verbose_name='Количество попыток')),
                ('correct_attempts', models.IntegerField(default=0, verbose_name='Правильные попытки')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('solved', 'Решена'), ('failed', 'Не решена')], default='new', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True, verbose_name='Последняя попытка')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_problems', to='users.assignment', verbose_name='Прототип задания')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='generated_problems', to=settings.AUTH_USER_MODEL, verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'Сгенерированная задача',
                'verbose_name_plural': 'Сгенерированные задачи',
            },
        ),
        migrations.CreateModel(
            name='ProblemAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer', models.TextField(verbose_name='Ответ ученика')),
                ('normalized_answer', models.JSONField(blank=True, null=True, verbose_name='Нормализованный ответ')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Правильно')),
                ('time_spent_seconds', models.IntegerField(default=0, verbose_name='Время решения (сек)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время попытки')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='users.generatedproblem', verbose_name='Задача')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'Попытка решения',
                'verbose_name_plural': 'Попытки решения',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='assignment',
            name='problem_generator',
            field=models.ForeignKey(blank=True, help_text='Если задание использует генератор задач', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='users.problemgenerator', verbose_name='Генератор задач'),
        ),
        migrations.CreateModel(
            name='StudentProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_attempts', models.IntegerField(default=0, verbose_name='Всего попыток')),
                ('correct_attempts', models.IntegerField(default=0, verbose_name='Правильных попыток')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Пройдено')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершено')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Начало изучения')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='users.assignment', verbose_name='Прототип задания')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to=settings.AUTH_USER_MODEL, verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'Прогресс ученика',
                'verbose_name_plural': 'Прогресс учеников',
            },
        ),
        migrations.AddIndex(
            model_name='generatedproblem',
            index=models.Index(fields=['student', 'status'], name='users_gener_student_ed3aa8_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedproblem',
            index=models.Index(fields=['assignment', 'student'], name='users_gener_assignm_79549d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='generatedproblem',
            unique_together={('assignment', 'student', 'task_data')},
        ),
        migrations.AlterUniqueTogether(
            name='studentprogress',
            unique_together={('student', 'assignment')},
        ),
    ]
