# Generated by Django 6.0.1 on 2026-01-29 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_problemgenerator_assignment_answer_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answeroption',
            options={'ordering': ['order'], 'verbose_name': 'Вариант ответа', 'verbose_name_plural': 'Варианты ответов'},
        ),
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ['order'], 'verbose_name': 'Задание', 'verbose_name_plural': 'Задания'},
        ),
        migrations.AlterModelOptions(
            name='testquestion',
            options={'ordering': ['order'], 'verbose_name': 'Вопрос теста', 'verbose_name_plural': 'Вопросы тестов'},
        ),
        migrations.AddField(
            model_name='assignment',
            name='theory_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.material', verbose_name='Теоретический материал'),
        ),
    ]
