# Generated by Django 6.0.1 on 2026-01-29 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_answeroption_options_alter_assignment_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='generatedproblem',
            unique_together=set(),
        ),
    ]
