# Generated by Django 6.0.1 on 2026-05-04 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_testquestion_image_svg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='linked_students',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Ученик'), ('admin', 'Администратор')], default='student', max_length=10, verbose_name='Роль'),
        ),
        migrations.DeleteModel(
            name='ParentProfile',
        ),
    ]
