# Generated by Django 6.0.1 on 2026-05-04 21:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_studentprofile_teacher_alter_user_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='tracking_mode',
            field=models.CharField(choices=[('auto', 'Автоматически (ученики решают на сайте)'), ('manual', 'Вручную (преподаватель отмечает)')], default='auto', help_text='manual — задачник, преподаватель сам отмечает решённые задачи', max_length=10, verbose_name='Режим прогресса'),
        ),
        migrations.CreateModel(
            name='ManualMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Решено')),
                ('marked_at', models.DateTimeField(auto_now=True, verbose_name='Дата отметки')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_marks', to='users.assignment', verbose_name='Прототип')),
                ('marked_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кто отметил')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='manual_marks', to=settings.AUTH_USER_MODEL, verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'Отметка (manual)',
                'verbose_name_plural': 'Отметки (manual)',
                'indexes': [models.Index(fields=['student', 'assignment'], name='users_manua_student_c21888_idx')],
                'unique_together': {('student', 'assignment')},
            },
        ),
    ]
