# Generated by Django 6.0.1 on 2026-05-05 00:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_course_tracking_mode_manualmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Для задачников — преподаватель, который ведёт курс. У общих курсов пусто.', limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_courses', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='course',
            name='short_description',
            field=models.TextField(blank=True, max_length=300, verbose_name='Краткое описание'),
        ),
    ]
