# Generated by Django 6.0.1 on 2026-05-05 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_course_owner_alter_course_short_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
    ]
