# Generated by Django 6.0.1 on 2026-05-05 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_user_email_remove_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='plaintext_password',
            field=models.CharField(blank=True, max_length=128, verbose_name='Пароль (видно админу)'),
        ),
    ]
