# Generated by Django 6.0.1 on 2026-05-05 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_user_plaintext_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='correct_answer',
            field=models.CharField(blank=True, help_text='Используется в курсах с ДЗ. Сравнение числовое, если число; иначе строкой.', max_length=255, verbose_name='Правильный ответ (для ДЗ)'),
        ),
        migrations.AlterField(
            model_name='course',
            name='tracking_mode',
            field=models.CharField(choices=[('auto', 'Автоматически (ученики решают на сайте)'), ('manual', 'Задачник (преподаватель отмечает)'), ('homework', 'Курс с ДЗ (преподаватель добавляет задачи, ученик вводит ответ)')], default='auto', help_text='manual — задачник, преподаватель сам отмечает решённые задачи', max_length=10, verbose_name='Режим прогресса'),
        ),
    ]
