# Generated by Django 6.0.1 on 2026-05-05 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_assignment_correct_answer_alter_course_tracking_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='image',
            field=models.ImageField(blank=True, help_text='Рисунок/чертёж к условию. Показывается над текстом условия.', null=True, upload_to='hw/', verbose_name='Картинка к задаче (для ДЗ)'),
        ),
    ]
