# Generated by Django 6.0.1 on 2026-05-05 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_assignment_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='school',
        ),
    ]
