# Generated by Django 6.0.1 on 2026-05-05 09:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_remove_studentprofile_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeworkAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=255, verbose_name='Ответ ученика')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Правильно')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hw_attempts', to='users.assignment')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='hw_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Попытка ученика',
                'verbose_name_plural': 'Попытки учеников',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['student', 'assignment'], name='users_homew_student_0d633b_idx')],
            },
        ),
    ]
