# Generated by Django 6.0.1 on 2026-05-05 09:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_homeworkattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='requires_review',
            field=models.BooleanField(default=False, help_text='Если включено — ученик отправляет развёрнутое решение (текст/фото), правильный ответ не нужен, задачу проверяет преподаватель.', verbose_name='Требует ручной проверки'),
        ),
        migrations.CreateModel(
            name='StudentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, verbose_name='Текст решения')),
                ('file', models.FileField(blank=True, null=True, upload_to='hw/submissions/', verbose_name='Прикреплённый файл (фото/PDF)')),
                ('status', models.CharField(choices=[('pending', 'На проверке'), ('accepted', 'Принято'), ('rejected', 'Вернуть на доработку')], default='pending', max_length=10, verbose_name='Статус')),
                ('teacher_comment', models.TextField(blank=True, verbose_name='Комментарий преподавателя')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='users.assignment')),
                ('reviewed_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Решение ученика',
                'verbose_name_plural': 'Решения учеников',
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['student', 'assignment'], name='users_stude_student_fbb841_idx')],
                'unique_together': {('student', 'assignment')},
            },
        ),
    ]
