# Generated by Django 6.0.1 on 2026-05-10 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_assignment_requires_review_studentsubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Например: «Вариант 1» или «Антоновка»', max_length=200, verbose_name='Название группы')),
                ('context_html', models.TextField(help_text='Общий текст + картинка (через <img>)', verbose_name='HTML контекста')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок в уроке')),
                ('fipi_ctx_id', models.CharField(blank=True, db_index=True, help_text='Для отслеживания происхождения', max_length=64, verbose_name='ID контекста на ФИПИ')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_groups', to='users.lesson', verbose_name='Урок (тема)')),
            ],
            options={
                'verbose_name': 'Группа задач (ОГЭ №1-5)',
                'verbose_name_plural': 'Группы задач (ОГЭ №1-5)',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='GroupSubQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_html', models.TextField(help_text='Текст с возможными таблицами/картинками', verbose_name='HTML вопроса')),
                ('correct_answer', models.CharField(help_text='Точное соответствие (с запятой для десятичных)', max_length=200, verbose_name='Правильный ответ')),
                ('t_type', models.CharField(blank=True, choices=[('T1', 'T1 — соответствие / идентификация'), ('T2', 'T2'), ('T3', 'T3'), ('T4', 'T4'), ('T5', 'T5 — оптимизация / сравнение')], max_length=5, verbose_name='Тип задания')),
                ('order', models.IntegerField(default=0, help_text='Обычно 1..5', verbose_name='Порядок в группе')),
                ('fipi_task_id', models.CharField(blank=True, db_index=True, max_length=32, verbose_name='ID задачи на ФИПИ')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_questions', to='users.taskgroup', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Подзадача группы',
                'verbose_name_plural': 'Подзадачи групп',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='GroupAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=255, verbose_name='Ответ ученика')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Правильно')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_attempts', to='users.studentprofile')),
                ('sub_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='users.groupsubquestion')),
            ],
            options={
                'verbose_name': 'Попытка по подзадаче (№1-5)',
                'verbose_name_plural': 'Попытки по подзадачам (№1-5)',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['student', 'sub_question'], name='users_group_student_1cbaa6_idx')],
            },
        ),
    ]
