# Generated by Django 6.0.1 on 2026-05-10 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_taskgroup_groupsubquestion_groupattempt'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='groupsubquestion',
            constraint=models.UniqueConstraint(fields=('group', 'order'), name='unique_subquestion_group_order'),
        ),
        migrations.AddConstraint(
            model_name='taskgroup',
            constraint=models.UniqueConstraint(fields=('lesson', 'order'), name='unique_taskgroup_lesson_order'),
        ),
    ]
