# Generated by Django 6.0.1 on 2026-05-28 11:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_clear_admin_plaintext_passwords'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитан')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата отметки')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_progress', to='users.lesson', verbose_name='Урок')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to=settings.AUTH_USER_MODEL, verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'Прогресс по уроку (теория)',
                'verbose_name_plural': 'Прогресс по урокам (теория)',
                'indexes': [models.Index(fields=['student', 'lesson'], name='users_lesso_student_eacd5b_idx')],
                'unique_together': {('student', 'lesson')},
            },
        ),
    ]
