# Generated by Django 6.0.1 on 2026-06-03 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_lesson_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_play_games',
            field=models.BooleanField(default=False, help_text='Если включено, пользователь видит /games/ и может создавать/играть партии. Не влияет на учебные курсы.', verbose_name='Доступ к разделу игр'),
        ),
        migrations.AddField(
            model_name='user',
            name='gamer_nickname',
            field=models.CharField(blank=True, default='', help_text='Имя, под которым пользователь будет виден сопернику в разделе игр. Если пусто — используется username.', max_length=30, verbose_name='Ник для игр'),
        ),
    ]
