# Generated by Django 6.0.1 on 2026-06-05 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_user_can_play_games_user_gamer_nickname'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=10, unique=True, verbose_name='Код варианта')),
                ('kind', models.CharField(choices=[('full', 'Полный вариант (1–19)'), ('short', 'Только задания 1–5')], default='full', max_length=10, verbose_name='Тип')),
                ('block_1_5_context_html', models.TextField(blank=True, verbose_name='Контекст 1–5')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('block_1_5_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='users.taskgroup', verbose_name='Исходная группа 1–5')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_variants', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'Вариант экзамена',
                'verbose_name_plural': 'Варианты экзамена',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamVariantSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.IntegerField(verbose_name='Номер слота (1..19)')),
                ('question_html', models.TextField(verbose_name='HTML условия')),
                ('correct_answer', models.CharField(max_length=255, verbose_name='Правильный ответ')),
                ('user_answer', models.CharField(blank=True, max_length=255, verbose_name='Ответ ученика')),
                ('is_correct', models.BooleanField(blank=True, null=True, verbose_name='Верно')),
                ('answered_at', models.DateTimeField(blank=True, null=True, verbose_name='Время ответа')),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='users.assignment', verbose_name='Источник: задание (для 6–19)')),
                ('sub_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='users.groupsubquestion', verbose_name='Источник: подзадача (для 1–5)')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='users.examvariant', verbose_name='Вариант')),
            ],
            options={
                'verbose_name': 'Слот варианта',
                'verbose_name_plural': 'Слоты вариантов',
                'ordering': ['slot'],
            },
        ),
        migrations.AddIndex(
            model_name='examvariant',
            index=models.Index(fields=['code'], name='users_examv_code_3cfdea_idx'),
        ),
        migrations.AddIndex(
            model_name='examvariantslot',
            index=models.Index(fields=['variant', 'slot'], name='users_examv_variant_737f57_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='examvariantslot',
            unique_together={('variant', 'slot')},
        ),
    ]
