# Generated by Django 6.0.1 on 2026-06-05 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_exam_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='examvariantslot',
            name='answer_type',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Тип ответа'),
        ),
        migrations.AddField(
            model_name='examvariantslot',
            name='choices',
            field=models.JSONField(blank=True, default=list, verbose_name='Варианты ответа (для single_choice)'),
        ),
        migrations.AddField(
            model_name='examvariantslot',
            name='task_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Номер задания ОГЭ'),
        ),
    ]
