# Generated by Django 6.0.1 on 2026-08-06 06:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_exam_slot_choices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examvariantslot',
            name='answered_at',
        ),
        migrations.RemoveField(
            model_name='examvariantslot',
            name='is_correct',
        ),
        migrations.RemoveField(
            model_name='examvariantslot',
            name='user_answer',
        ),
        migrations.CreateModel(
            name='ExamVariantAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer', models.CharField(blank=True, max_length=255, verbose_name='Ответ ученика')),
                ('is_correct', models.BooleanField(blank=True, null=True, verbose_name='Верно')),
                ('answered_at', models.DateTimeField(auto_now=True, verbose_name='Время ответа')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='users.examvariantslot', verbose_name='Слот')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_variant_answers', to=settings.AUTH_USER_MODEL, verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'Ответ по варианту',
                'verbose_name_plural': 'Ответы по варианту',
                'constraints': [models.UniqueConstraint(fields=('slot', 'user'), name='uniq_variant_slot_user')],
            },
        ),
    ]
