# Generated by Django 6.0.1 on 2026-08-06 06:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_remove_examvariantslot_answered_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupattempt',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_attempts', to=settings.AUTH_USER_MODEL),
        ),
    ]
