# Generated by Django 6.0.1 on 2026-08-07 06:54

from django.db import migrations, models


def backfill_is_public(apps, schema_editor):
    """Существующее поведение 1-в-1: auto — публичный, manual/homework — приватный."""
    Course = apps.get_model('users', 'Course')
    Course.objects.filter(tracking_mode='auto').update(is_public=True)
    Course.objects.exclude(tracking_mode='auto').update(is_public=False)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_alter_groupattempt_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_public',
            field=models.BooleanField(default=False, help_text='True — виден всем в каталоге, открытая запись (общие ОГЭ-курсы). False — приватный: только владелец и записанные им ученики.', verbose_name='Публичный (в общем каталоге)'),
        ),
        migrations.RunPython(backfill_is_public, migrations.RunPython.noop),
    ]
