# Generated by Django 6.0.1 on 2026-08-07 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_course_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testquestion',
            name='question_type',
            field=models.CharField(choices=[('single_choice', 'Один правильный ответ'), ('multiple_choice', 'Несколько правильных ответов'), ('true_false', 'Верно/Неверно'), ('number', 'Числовой ответ')], default='single_choice', max_length=20, verbose_name='Тип вопроса'),
        ),
    ]
