# Generated by Django 6.0.1 on 2026-08-07 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_alter_testquestion_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='testquestion',
            name='image',
            field=models.ImageField(blank=True, help_text='Загруженная картинка (приоритетнее image_svg).', null=True, upload_to='prototypes/', verbose_name='Картинка к вопросу'),
        ),
    ]
