# Generated by Django 6.0.1 on 2026-08-31 17:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_testquestion_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Заголовок')),
                ('url', models.URLField(max_length=500, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])], verbose_name='Адрес')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлена')),
                ('student', models.ForeignKey(blank=True, help_text='Пусто — ссылку увидят все ученики этого преподавателя.', limit_choices_to={'role': 'student'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='links', to=settings.AUTH_USER_MODEL, verbose_name='Ученик')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='given_links', to=settings.AUTH_USER_MODEL, verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Ссылка для ученика',
                'verbose_name_plural': 'Ссылки для учеников',
                'ordering': ['order', 'id'],
            },
        ),
    ]
