# Generated by Django 6.0.1 on 2026-08-31 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_studentlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='due_date',
            field=models.DateField(blank=True, help_text='Только для курсов с ДЗ. Пусто — без срока.', null=True, verbose_name='Срок сдачи'),
        ),
    ]
