# Generated by Django 6.0.1 on 2026-09-01 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_lesson_due_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentsubmission',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='studentsubmission',
            name='attempt',
            field=models.PositiveIntegerField(default=1, verbose_name='Номер попытки'),
        ),
        migrations.AddField(
            model_name='studentsubmission',
            name='is_latest',
            field=models.BooleanField(default=True, verbose_name='Текущая попытка'),
        ),
        migrations.AlterUniqueTogether(
            name='studentsubmission',
            unique_together={('student', 'assignment', 'attempt')},
        ),
        migrations.AddIndex(
            model_name='studentsubmission',
            index=models.Index(fields=['student', 'assignment', 'is_latest'], name='users_stude_student_faca08_idx'),
        ),
    ]
