# Generated by Django 6.0.1 on 2026-09-01 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_alter_studentsubmission_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='cutoff_date',
            field=models.DateField(blank=True, help_text='После этой даты работу уже не принять. Пусто — принимаем и с опозданием.', null=True, verbose_name='Приём закрыт после'),
        ),
    ]
