# Generated by Django 6.0.1 on 2026-09-01 04:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_lesson_cutoff_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeworkExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Личный срок')),
                ('cutoff_date', models.DateField(blank=True, null=True, verbose_name='Личный приём до')),
                ('reason', models.CharField(blank=True, help_text='Через месяц вы сами не вспомните, почему у него срок другой.', max_length=200, verbose_name='Причина')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Когда')),
                ('granted_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кто продлил')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extensions', to='users.lesson', verbose_name='Домашка')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='hw_extensions', to=settings.AUTH_USER_MODEL, verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'Продление срока',
                'verbose_name_plural': 'Продления сроков',
                'indexes': [models.Index(fields=['lesson', 'student'], name='users_homew_lesson__5a82be_idx')],
                'unique_together': {('lesson', 'student')},
            },
        ),
    ]
