# Generated by Django 6.0.1 on 2026-09-01 16:48

import django.db.models.deletion
import users.uploads
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_homeworkextension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsubmission',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='hw/submissions/', validators=[users.uploads.validate_homework_file], verbose_name='Прикреплённый файл (фото/PDF)'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('submitted', 'Прислали работу'), ('reviewed', 'Работу проверили')], max_length=20, verbose_name='Событие')),
                ('text', models.CharField(max_length=300, verbose_name='Текст')),
                ('url', models.CharField(blank=True, max_length=500, verbose_name='Ссылка')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Когда')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Кому')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read', '-created_at'], name='users_notif_user_id_f3f50a_idx')],
            },
        ),
    ]
