# Generated by Django 6.0.1 on 2026-09-04 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_alter_notification_kind_thread_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='key',
            field=models.CharField(blank=True, max_length=120, verbose_name='Ключ повторности'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(condition=models.Q(('key', ''), _negated=True), fields=('user', 'kind', 'key'), name='uniq_notification_key'),
        ),
    ]
