# Generated by Django 6.0.1 on 2026-09-04 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_notification_key_notification_uniq_notification_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('submitted', 'Прислали работу'), ('reviewed', 'Работу проверили'), ('message', 'Новое сообщение'), ('due_soon', 'Срок подходит'), ('due_passed', 'Срок вышел'), ('digest', 'Сводка за день')], max_length=20, verbose_name='Событие'),
        ),
    ]
