# Generated by Django 6.0.1 on 2026-09-04 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_alter_notification_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, default=0, help_text='Сколько набрано за этот номер', max_digits=6, verbose_name='Балл')),
                ('max_value', models.DecimalField(decimal_places=2, default=1, max_digits=6, verbose_name='Из скольких')),
                ('penalty', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Снято за опоздание')),
                ('graded_at', models.DateTimeField(auto_now=True, verbose_name='Когда поставлена')),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grades_given', to=settings.AUTH_USER_MODEL, verbose_name='Кто поставил')),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grade', to='users.studentsubmission', verbose_name='Работа')),
            ],
            options={
                'verbose_name': 'Оценка',
                'verbose_name_plural': 'Оценки',
                'indexes': [models.Index(fields=['submission'], name='users_grade_submiss_a941d0_idx')],
            },
        ),
    ]
