# Generated by Django 6.0.1 on 2026-09-05 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0045_grade_student_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='cutoff_offset_days',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Приём: дней от записи'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='due_offset_days',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Например 7 — сдать в течение недели после записи на курс', null=True, verbose_name='Срок: дней от записи'),
        ),
    ]
