# Generated by Django 6.0.1 on 2026-09-05 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0046_lesson_relative_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='sequential',
            field=models.BooleanField(default=False, help_text='Следующий урок открывается, когда пройден предыдущий.', verbose_name='Последовательный курс'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='ends_at',
            field=models.DateField(blank=True, help_text='Пусто — без ограничения. День включительно.', null=True, verbose_name='Доступ по'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='starts_at',
            field=models.DateField(blank=True, help_text='Пусто — сразу.', null=True, verbose_name='Доступ с'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='available_from',
            field=models.DateField(blank=True, help_text='Пусто — доступен сразу.', null=True, verbose_name='Откроется с'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='unlock_after',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unlocks', to='users.lesson', verbose_name='Откроется после урока'),
        ),
    ]
