"""
Django settings for tutor_core project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Загружаем переменные из файла .env
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-c5!ba$1homzlg3yci=n@jrntp2x1nould$%_b_zitjg2hi^9y&')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG') == 'True'

ALLOWED_HOSTS = []


# Application definition

# tutor_core/settings.py

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Сторонние приложения
    'rest_framework',  # <-- ДОБАВЬТЕ ЭТУ СТРОКУ ЗДЕСЬ
    
    # Ваши приложения
    'users',  # Ваше приложение
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'tutor_core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'tutor_core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'ru-ru'  # <--- Изменили на русский

TIME_ZONE = 'Europe/Moscow'  # <--- Изменили на московское время

USE_I18N = True

USE_TZ = True


# ==================== Статические файлы (CSS, JavaScript, Images) ====================
# https://docs.djangoproject.com/en/6.0/howto/static-files/

# URL-префикс для статических файлов
STATIC_URL = 'static/'

# Папка для сбора ВСЕХ статических файлов командой collectstatic
STATIC_ROOT = BASE_DIR / 'staticfiles'  # <--- ДОБАВЬТЕ ЭТУ СТРОКУ

# Папки, где Django ищет статические файлы в режиме разработки
STATICFILES_DIRS = [
    BASE_DIR / "static",           # Глобальная папка static
    BASE_DIR / "users" / "static", # Папка static в приложении users
]

# ==================== Медиафайлы (загружаемые пользователями) ====================
# URL-префикс для медиафайлов
MEDIA_URL = 'media/'

# Физический путь к папке с медиафайлами
MEDIA_ROOT = BASE_DIR / 'media'

# ==================== Кастомная модель пользователя ====================
# Указываем Django использовать нашу кастомную модель пользователя
AUTH_USER_MODEL = 'users.User'