"""
Django settings for tutor_core project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv
from urllib.parse import urlparse

# Загружаем переменные из файла .env
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "SECRET_KEY",
    "django-insecure-c5!ba$1homzlg3yci=n@jrntp2x1nould$%_b_zitjg2hi^9y&",
)

# Переключатель DEBUG через переменную окружения:
# локально DJANGO_DEBUG обычно не задан → DEBUG = True
# на сервере зададим DJANGO_DEBUG=False → DEBUG = False
DEBUG = os.environ.get("DJANGO_DEBUG", "True") == "True"

ALLOWED_HOSTS = [
    "web-production-b8e1c.up.railway.app",
    "127.0.0.1",
    "localhost",
]
CSRF_TRUSTED_ORIGINS = [
    "https://web-production-b8e1c.up.railway.app",
]

# Application definition

INSTALLED_APPS = [
    # django-unfold должен идти ДО django.contrib.admin
    "unfold",
    "unfold.contrib.filters",
    "unfold.contrib.forms",
    "unfold.contrib.inlines",

    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Сторонние приложения
    "rest_framework",

    # Ваши приложения
    "users",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "tutor_core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "tutor_core.wsgi.application"

# Database
# Пока SQLite; при переходе на PostgreSQL на хостинге
# заменим этот блок на чтение DATABASE_URL.
DATABASE_URL = os.getenv("DATABASE_URL")

if DATABASE_URL and not DEBUG:
    parsed = urlparse(DATABASE_URL)
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": parsed.path[1:],
            "USER": parsed.username,
            "PASSWORD": parsed.password,
            "HOST": parsed.hostname,
            "PORT": parsed.port or "5432",
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# Валидаторы отключены: пароли учеников выдаёт сам преподаватель,
# простые пароли вроде "polina" — это нормально и удобно.
AUTH_PASSWORD_VALIDATORS = []

# Internationalization

LANGUAGE_CODE = "ru-ru"
TIME_ZONE = "Europe/Moscow"
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)

STATIC_URL = "/static/"

# Папка для collectstatic (для деплоя)
STATIC_ROOT = BASE_DIR / "staticfiles"

# Папки для статических файлов в разработке
STATICFILES_DIRS = [
    BASE_DIR / "static",
    BASE_DIR / "users" / "static",
]

# Медиафайлы

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Разрешаем iframe с того же домена — нужно для встроенного просмотра PDF.
X_FRAME_OPTIONS = "SAMEORIGIN"

# Кастомная модель пользователя
AUTH_USER_MODEL = "users.User"

# ===== django-unfold (красивая админка) =====
UNFOLD = {
    "SITE_TITLE": "Tutor Site — админка",
    "SITE_HEADER": "Tutor Site",
    "SITE_SUBHEADER": "Панель управления",
    "SITE_SYMBOL": "school",  # Material Symbols icon
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,
    "THEME": None,  # None = пользователь сам переключает свет/тьму
    "COLORS": {
        "primary": {
            "50": "239 246 255",
            "100": "219 234 254",
            "200": "191 219 254",
            "300": "147 197 253",
            "400": "96 165 250",
            "500": "59 130 246",
            "600": "37 99 235",
            "700": "29 78 216",
            "800": "30 64 175",
            "900": "30 58 138",
            "950": "23 37 84",
        },
    },
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": True,
        "navigation": [
            {
                "title": "Обучение",
                "separator": True,
                "items": [
                    {
                        "title": "Курсы",
                        "icon": "menu_book",
                        "link": "/admin/users/course/",
                    },
                    {
                        "title": "Модули",
                        "icon": "view_module",
                        "link": "/admin/users/module/",
                    },
                    {
                        "title": "Уроки",
                        "icon": "article",
                        "link": "/admin/users/lesson/",
                    },
                    {
                        "title": "Задания",
                        "icon": "assignment",
                        "link": "/admin/users/assignment/",
                    },
                ],
            },
            {
                "title": "Пользователи",
                "separator": True,
                "items": [
                    {
                        "title": "Пользователи",
                        "icon": "person",
                        "link": "/admin/users/user/",
                    },
                    {
                        "title": "Преподаватели",
                        "icon": "school",
                        "link": "/admin/users/teacherprofile/",
                    },
                    {
                        "title": "Профили учеников",
                        "icon": "badge",
                        "link": "/admin/users/studentprofile/",
                    },
                    {
                        "title": "Записи на курсы",
                        "icon": "how_to_reg",
                        "link": "/admin/users/enrollment/",
                    },
                ],
            },
            {
                "title": "Материалы",
                "separator": True,
                "items": [
                    {
                        "title": "Категории",
                        "icon": "folder",
                        "link": "/admin/users/materialcategory/",
                    },
                    {
                        "title": "Материалы",
                        "icon": "description",
                        "link": "/admin/users/material/",
                    },
                ],
            },
        ],
    },
}
