# Generated by Django 6.0.1 on 2026-08-29 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoridorGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=10, unique=True, verbose_name='Код партии')),
                ('state', models.JSONField(default=dict, verbose_name='Состояние партии')),
                ('status', models.CharField(choices=[('waiting', 'Ждёт соперника'), ('active', 'Идёт'), ('finished', 'Завершена')], default='waiting', max_length=10, verbose_name='Статус')),
                ('winner', models.CharField(blank=True, default='', help_text='red, blue или пусто, если партия не завершена.', max_length=4, verbose_name='Победитель')),
                ('last_move', models.JSONField(blank=True, null=True, verbose_name='Последний ход')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('blue_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quoridor_as_blue', to=settings.AUTH_USER_MODEL, verbose_name='Синий')),
                ('red_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quoridor_as_red', to=settings.AUTH_USER_MODEL, verbose_name='Красный')),
            ],
            options={
                'verbose_name': 'Партия «Заборы»',
                'verbose_name_plural': 'Партии «Заборы»',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['code'], name='quoridor_qu_code_1df1a6_idx')],
            },
        ),
    ]
