# Generated by Django 6.0.1 on 2026-08-29 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoridor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoridorgame',
            name='status',
            field=models.CharField(choices=[('waiting', 'Ждёт соперника'), ('active', 'Идёт'), ('finished', 'Завершена'), ('cancelled', 'Отменена')], default='waiting', max_length=10, verbose_name='Статус'),
        ),
    ]
