# Generated by Django 6.0.1 on 2026-08-29 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoridor', '0002_alter_quoridorgame_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoridorgame',
            name='access',
            field=models.CharField(choices=[('link', 'Только по ссылке'), ('open', 'Видна всем в лобби')], default='link', help_text='Приватная партия не показывается в лобби: войти можно только по ссылке от создателя.', max_length=8, verbose_name='Доступ'),
        ),
    ]
