# Generated by Django 6.0.1 on 2026-06-03 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('games_enabled', models.BooleanField(default=False, help_text='Если выключено — /games/ отдаёт 404 для всех, кроме суперпользователей. Меняется без рестарта сервера.', verbose_name='Раздел игр включён')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Настройки раздела игр',
                'verbose_name_plural': 'Настройки раздела игр',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=10, unique=True, verbose_name='Код партии')),
                ('board', models.JSONField(default=list, verbose_name='Доска (9×9)')),
                ('big_board', models.JSONField(default=list, verbose_name='Большое поле')),
                ('next_local', models.IntegerField(blank=True, null=True, verbose_name='Куда обязан ходить')),
                ('current', models.CharField(default='X', max_length=1, verbose_name='Чей сейчас ход')),
                ('status', models.CharField(choices=[('waiting', 'Ждёт соперника'), ('active', 'Идёт'), ('finished', 'Завершена')], default='waiting', max_length=10, verbose_name='Статус')),
                ('winner', models.CharField(blank=True, default='', help_text='X, O, D (ничья) или пусто (партия не завершена).', max_length=4, verbose_name='Победитель')),
                ('last_move', models.JSONField(blank=True, null=True, verbose_name='Последний ход')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('o_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games_as_o', to=settings.AUTH_USER_MODEL, verbose_name='Игрок O')),
                ('x_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games_as_x', to=settings.AUTH_USER_MODEL, verbose_name='Игрок X')),
            ],
            options={
                'verbose_name': 'Партия UTTT',
                'verbose_name_plural': 'Партии UTTT',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['code'], name='games_game_code_1dd278_idx')],
            },
        ),
    ]
