# Generated by Django 6.0.1 on 2026-06-03 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_local',
            field=models.BooleanField(default=False, help_text='Два игрока за одним компьютером. Ходы делает один и тот же пользователь, joining не требуется.', verbose_name='Локальная (hot-seat)'),
        ),
        migrations.AddField(
            model_name='game',
            name='parent_game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rematches', to='games.game', verbose_name='Партия-предок (реванш)'),
        ),
        migrations.AddField(
            model_name='game',
            name='variant',
            field=models.CharField(choices=[('classic', 'Классика'), ('long', 'Долгая дорога')], default='classic', max_length=10, verbose_name='Вариант правил'),
        ),
    ]
