# Generated by Django 6.0.1 on 2026-08-31 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game_is_local_game_parent_game_game_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='bot_level',
            field=models.CharField(blank=True, choices=[('easy', 'слабый'), ('medium', 'средний'), ('hard', 'сильный')], default='', max_length=10, verbose_name='Уровень компьютера'),
        ),
        migrations.AddField(
            model_name='game',
            name='bot_side',
            field=models.CharField(blank=True, default='', help_text='X или O, если соперник — компьютер. Пусто у обычных партий.', max_length=1, verbose_name='Сторона компьютера'),
        ),
    ]
