# Generated by Django 6.0.1 on 2026-09-05 11:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0043_messenger'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('visibility', models.CharField(choices=[('private', 'Личная — вижу только я'), ('shared', 'Общая — видят все, кто вошёл на сайт'), ('public', 'Открытая — видна и гостям')], default='private', max_length=10, verbose_name='Кому видна')),
                ('kind', models.CharField(choices=[('math', 'Математика — ответ проверяется как формула'), ('text', 'Обычный текст — слова, определения, перевод')], default='text', max_length=10, verbose_name='Вид материала')),
                ('reverse_enabled', models.BooleanField(default=False, help_text='Кроме «лицо → оборот» появится «оборот → лицо». Полезно для слов и переводов, вредно для определений.', verbose_name='Спрашивать и в обратную сторону')),
                ('ask_to_type', models.BooleanField(default=False, help_text='Вместо «переверни и оцени себя» ученик вводит ответ, и он проверяется автоматически.', verbose_name='Просить набрать ответ')),
                ('desired_retention', models.FloatField(default=0.9, help_text='Доля карточек, которые ученик должен помнить к моменту повторения. Больше — надёжнее, но повторений больше.', verbose_name='Желаемая прочность')),
                ('exam_date', models.DateField(blank=True, help_text='Если указана, карточка никогда не назначается на «после» неё. Без этого интервалы дорастают до десятков лет.', null=True, verbose_name='Дата экзамена')),
                ('new_per_day', models.IntegerField(default=20, help_text='Сколько незнакомых карточек показывать за сутки.', verbose_name='Новых карточек в день')),
                ('reviews_per_day', models.IntegerField(default=200, help_text='Потолок на уже начатые карточки. 0 — без ограничения.', verbose_name='Повторений в день')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменена')),
                ('lesson', models.ForeignKey(blank=True, help_text='Пусто — колода живёт в разделе карточек сама по себе.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decks', to='users.lesson', verbose_name='Урок')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decks', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Колода карточек',
                'verbose_name_plural': 'Колоды карточек',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front', models.TextField(help_text='Вопрос. Формулы — в долларах: $x^2$.', verbose_name='Лицевая сторона')),
                ('back', models.TextField(help_text='Ответ. Коротко, один факт.', verbose_name='Оборот')),
                ('hint', models.TextField(blank=True, help_text='Необязательно: пример, уточнение или разбор.', verbose_name='Подсказка')),
                ('accepted', models.TextField(blank=True, help_text='Другие верные написания ответа, по одному в строке.', verbose_name='Ещё засчитывать')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='cards.deck', verbose_name='Колода')),
            ],
            options={
                'verbose_name': 'Карточка',
                'verbose_name_plural': 'Карточки',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CardReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.SmallIntegerField(choices=[(0, 'Лицо → оборот'), (1, 'Оборот → лицо')], default=0, verbose_name='Направление')),
                ('rating', models.SmallIntegerField(choices=[(1, 'Опять'), (2, 'Трудно'), (3, 'Хорошо'), (4, 'Легко')], verbose_name='Оценка')),
                ('reviewed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Когда')),
                ('duration_ms', models.IntegerField(blank=True, help_text='Нужно оптимизатору весов. Пишется автоматически.', null=True, verbose_name='Сколько думал, мс')),
                ('typed', models.CharField(blank=True, max_length=300, verbose_name='Введённый ответ')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='cards.card', verbose_name='Карточка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'Повторение',
                'verbose_name_plural': 'Журнал повторений',
                'ordering': ['-reviewed_at'],
                'indexes': [models.Index(fields=['user', 'reviewed_at'], name='cards_review_when_idx')],
            },
        ),
        migrations.CreateModel(
            name='CardState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.SmallIntegerField(choices=[(0, 'Лицо → оборот'), (1, 'Оборот → лицо')], default=0, verbose_name='Направление')),
                ('state', models.SmallIntegerField(choices=[(1, 'Изучается'), (2, 'На повторении'), (3, 'Переучивается')], default=1, verbose_name='Стадия')),
                ('step', models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Шаг обучения')),
                ('stability', models.FloatField(blank=True, null=True, verbose_name='Прочность')),
                ('difficulty', models.FloatField(blank=True, null=True, verbose_name='Трудность')),
                ('due', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Показать не раньше')),
                ('last_review', models.DateTimeField(blank=True, null=True, verbose_name='Последний показ')),
                ('reps', models.IntegerField(default=0, verbose_name='Показов')),
                ('lapses', models.IntegerField(default=0, verbose_name='Забываний')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Впервые показана')),
                ('suspended', models.BooleanField(default=False, help_text='Карточка не показывается, пока её не вернут в оборот.', verbose_name='Отложена')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='cards.card', verbose_name='Карточка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_states', to=settings.AUTH_USER_MODEL, verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'Состояние карточки',
                'verbose_name_plural': 'Состояния карточек',
                'indexes': [models.Index(fields=['user', 'due'], name='cards_state_due_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'card', 'direction'), name='cards_state_unique')],
            },
        ),
    ]
