# Generated by Django 6.0.1 on 2026-09-05 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def перенести_способ_вопроса(apps, schema_editor):
    """Флаг «просить набрать ответ» превращается в способ вопроса.

    Раньше выбор был двоичным: переворот или ввод. Теперь способов три, и
    старую настройку надо перенести, а не потерять — иначе колоды, где
    репетитор просил вводить ответ, молча вернулись бы к перевороту.
    """
    Deck = apps.get_model('cards', 'Deck')
    Deck.objects.filter(ask_to_type=True).update(ask_mode='typed')


def вернуть_способ_вопроса(apps, schema_editor):
    Deck = apps.get_model('cards', 'Deck')
    Deck.objects.filter(ask_mode='typed').update(ask_to_type=True)


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='ask_mode',
            field=models.CharField(choices=[('flip', 'Переворот — вспомнил и оценил себя'), ('choice', 'Выбор из вариантов'), ('typed', 'Ввод ответа')], default='flip', max_length=10, verbose_name='Как спрашивать'),
        ),
        migrations.RunPython(перенести_способ_вопроса, вернуть_способ_вопроса),
        migrations.RemoveField(
            model_name='deck',
            name='ask_to_type',
        ),
        migrations.AddField(
            model_name='card',
            name='distractors',
            field=models.TextField(blank=True, help_text='Для вопросов с выбором. По одному в строке, сколько угодно.', verbose_name='Неверные варианты'),
        ),
        migrations.AddField(
            model_name='deck',
            name='back_lang',
            field=models.CharField(blank=True, choices=[('', 'Не указан'), ('ru', 'Русский'), ('en', 'Английский'), ('zh', 'Китайский'), ('de', 'Немецкий'), ('fr', 'Французский'), ('es', 'Испанский'), ('la', 'Латынь')], default='', max_length=8, verbose_name='Язык оборота'),
        ),
        migrations.AddField(
            model_name='deck',
            name='check_mode',
            field=models.CharField(choices=[('auto', 'Сверяет сайт'), ('self', 'Показать верный ответ, ученик решает сам')], default='auto', help_text='Имеет значение только при вводе ответа.', max_length=10, verbose_name='Кто проверяет ввод'),
        ),
        migrations.AddField(
            model_name='deck',
            name='front_lang',
            field=models.CharField(blank=True, choices=[('', 'Не указан'), ('ru', 'Русский'), ('en', 'Английский'), ('zh', 'Китайский'), ('de', 'Немецкий'), ('fr', 'Французский'), ('es', 'Испанский'), ('la', 'Латынь')], default='', max_length=8, verbose_name='Язык лицевой стороны'),
        ),
        migrations.CreateModel(
            name='SchedulerWeights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameters', models.JSONField(default=list, verbose_name='Веса модели')),
                ('reviews_used', models.IntegerField(default=0, verbose_name='На скольких повторениях обучено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Пересчитано')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='Пометка')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scheduler_weights', to=settings.AUTH_USER_MODEL, verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'Веса планировщика',
                'verbose_name_plural': 'Веса планировщика',
            },
        ),
    ]
