# Generated by Django 6.0.1 on 2026-09-05 16:52

import django.db.models.deletion
from django.conf import settings
import secrets

from django.db import migrations, models


def раздать_ключи(apps, schema_editor):
    """Каждой существующей колоде — свой ключ ссылки."""
    Deck = apps.get_model('cards', 'Deck')
    for колода in Deck.objects.filter(share_token=''):
        колода.share_token = secrets.token_urlsafe(16)
        колода.save(update_fields=['share_token'])


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_remove_deck_ask_to_type_card_distractors_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deck',
            name='ask_mode',
        ),
        migrations.RemoveField(
            model_name='deck',
            name='back_lang',
        ),
        migrations.RemoveField(
            model_name='deck',
            name='front_lang',
        ),
        migrations.RemoveField(
            model_name='deck',
            name='kind',
        ),
        migrations.RemoveField(
            model_name='deck',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='deck',
            name='visibility',
        ),
        # Ключ добавляется без уникальности, заполняется, и только потом
        # становится уникальным: иначе все существующие колоды получили бы
        # пустую строку и столкнулись между собой.
        migrations.AddField(
            model_name='deck',
            name='share_token',
            field=models.CharField(blank=True, default='', help_text='Часть адреса, по которому колоду открывают другие.', max_length=22, verbose_name='Ключ ссылки'),
        ),
        migrations.RunPython(раздать_ключи, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='deck',
            name='share_token',
            field=models.CharField(blank=True, help_text='Часть адреса, по которому колоду открывают другие.', max_length=22, unique=True, verbose_name='Ключ ссылки'),
        ),
        migrations.CreateModel(
            name='DeckShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened_at', models.DateTimeField(auto_now_add=True, verbose_name='Открыта')),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='cards.deck', verbose_name='Колода')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deck_shares', to=settings.AUTH_USER_MODEL, verbose_name='Кому открыта')),
            ],
            options={
                'verbose_name': 'Доступ по ссылке',
                'verbose_name_plural': 'Доступы по ссылке',
                'constraints': [models.UniqueConstraint(fields=('deck', 'user'), name='cards_share_unique')],
            },
        ),
    ]
