# Generated by Django 6.0.1 on 2026-09-09 20:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_remove_deck_ask_mode_remove_deck_back_lang_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='cardreview',
            name='cards_review_when_idx',
        ),
        migrations.RemoveField(
            model_name='schedulerweights',
            name='user',
        ),
        migrations.RemoveIndex(
            model_name='cardstate',
            name='cards_state_due_idx',
        ),
        migrations.RemoveField(
            model_name='deck',
            name='desired_retention',
        ),
        migrations.RemoveField(
            model_name='deck',
            name='exam_date',
        ),
        migrations.RemoveField(
            model_name='deck',
            name='new_per_day',
        ),
        migrations.RemoveField(
            model_name='deck',
            name='reviews_per_day',
        ),
        migrations.AddField(
            model_name='cardstate',
            name='misses',
            field=models.IntegerField(default=0, verbose_name='Ошибок'),
        ),
        migrations.AddField(
            model_name='cardstate',
            name='section',
            field=models.SmallIntegerField(choices=[(0, 'Не разобрано'), (1, 'Трудно'), (2, 'Сложно'), (3, 'Нормально'), (4, 'Легко')], default=0, verbose_name='Секция'),
        ),
        migrations.AddField(
            model_name='cardstate',
            name='shows',
            field=models.IntegerField(default=0, verbose_name='Показов'),
        ),
        migrations.AddField(
            model_name='deck',
            name='round_size',
            field=models.IntegerField(default=7, help_text='Сколько карточек показывать за один подход. В просмотре и тесте раундов нет.', verbose_name='Карточек за раунд'),
        ),
        migrations.AddIndex(
            model_name='cardstate',
            index=models.Index(fields=['user', 'section'], name='cards_state_sect_idx'),
        ),
        migrations.RemoveField(
            model_name='cardreview',
            name='card',
        ),
        migrations.RemoveField(
            model_name='cardreview',
            name='user',
        ),
        migrations.DeleteModel(
            name='SchedulerWeights',
        ),
        migrations.RemoveField(
            model_name='cardstate',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='cardstate',
            name='due',
        ),
        migrations.RemoveField(
            model_name='cardstate',
            name='lapses',
        ),
        migrations.RemoveField(
            model_name='cardstate',
            name='last_review',
        ),
        migrations.RemoveField(
            model_name='cardstate',
            name='reps',
        ),
        migrations.RemoveField(
            model_name='cardstate',
            name='stability',
        ),
        migrations.RemoveField(
            model_name='cardstate',
            name='started_at',
        ),
        migrations.RemoveField(
            model_name='cardstate',
            name='state',
        ),
        migrations.RemoveField(
            model_name='cardstate',
            name='step',
        ),
        migrations.RemoveField(
            model_name='cardstate',
            name='suspended',
        ),
        migrations.DeleteModel(
            name='CardReview',
        ),
    ]
