# Generated by Django 6.0.1 on 2026-06-11 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0027_exam_slot_choices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=10, unique=True, verbose_name='Код доски')),
                ('title', models.CharField(blank=True, default='', max_length=120, verbose_name='Название')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boards', to='users.lesson', verbose_name='Урок (необязательно)')),
                ('members', models.ManyToManyField(blank=True, help_text='Пользователи, присоединившиеся к доске по коду.', related_name='boards_joined', to=settings.AUTH_USER_MODEL, verbose_name='Участники')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boards_owned', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Доска',
                'verbose_name_plural': 'Доски',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='BoardElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_id', models.CharField(db_index=True, max_length=40, verbose_name='ID элемента')),
                ('type', models.CharField(choices=[('freehand', 'Рисунок от руки'), ('line', 'Линия'), ('rect', 'Прямоугольник'), ('ellipse', 'Эллипс'), ('text', 'Текст'), ('latex', 'Формула (LaTeX)'), ('geogebra', 'ГеоГебра'), ('image', 'Изображение')], max_length=12, verbose_name='Тип')),
                ('data', models.JSONField(default=dict, verbose_name='Данные')),
                ('z_index', models.IntegerField(default=0, verbose_name='Слой (z)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='board_elements', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='board.board', verbose_name='Доска')),
            ],
            options={
                'verbose_name': 'Элемент доски',
                'verbose_name_plural': 'Элементы доски',
                'ordering': ['z_index', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='board',
            index=models.Index(fields=['code'], name='board_board_code_bf912d_idx'),
        ),
        migrations.AddIndex(
            model_name='boardelement',
            index=models.Index(fields=['board', 'element_id'], name='board_board_board_i_6a3027_idx'),
        ),
        migrations.AddConstraint(
            model_name='boardelement',
            constraint=models.UniqueConstraint(fields=('board', 'element_id'), name='uniq_board_element_id'),
        ),
    ]
