# Generated by Django 6.0.1 on 2026-08-05 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='default_role',
            field=models.CharField(choices=[('viewer', 'Наблюдатель'), ('editor', 'Редактор')], default='editor', help_text='Что могут делать зашедшие по ссылке, если им не назначена личная роль.', max_length=8, verbose_name='Роль по ссылке'),
        ),
        migrations.AddField(
            model_name='board',
            name='roles',
            field=models.JSONField(blank=True, default=dict, verbose_name='Личные роли'),
        ),
    ]
