# Generated by Django 6.0.1 on 2026-08-06 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_board_default_role_board_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('add', 'Добавлено'), ('update', 'Изменено'), ('delete', 'Удалено')], max_length=8, verbose_name='Действие')),
                ('element_id', models.CharField(db_index=True, max_length=40, verbose_name='ID элемента')),
                ('element_type', models.CharField(blank=True, default='', max_length=16, verbose_name='Тип элемента')),
                ('payload', models.JSONField(blank=True, null=True, verbose_name='Снимок (для восстановления)')),
                ('by', models.IntegerField(blank=True, null=True, verbose_name='Кто (user id)')),
                ('label', models.CharField(blank=True, default='', max_length=80, verbose_name='Кто (подпись)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Когда')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='board.board', verbose_name='Доска')),
            ],
            options={
                'verbose_name': 'История доски',
                'verbose_name_plural': 'История доски',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['board', 'id'], name='board_board_board_i_fa37c2_idx')],
            },
        ),
    ]
