# Generated by Django 6.0.1 on 2026-08-12 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_boardhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='password_enabled',
            field=models.BooleanField(default=False, verbose_name='Требовать пароль при входе'),
        ),
        migrations.AddField(
            model_name='board',
            name='password_hash',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Пароль (хеш)'),
        ),
    ]
