# Generated by Django 6.0.1 on 2026-08-20 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_alter_boardelement_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='banned',
            field=models.JSONField(blank=True, default=list, verbose_name='Убранные с доски'),
        ),
    ]
