# Generated by Django 6.0.1 on 2026-08-20 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_alter_boardelement_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardelement',
            name='type',
            field=models.CharField(choices=[('freehand', 'Рисунок от руки'), ('line', 'Линия'), ('arrow', 'Стрелка'), ('rect', 'Прямоугольник'), ('ellipse', 'Эллипс'), ('shape', 'Фигура'), ('text', 'Текст с формулами'), ('textbox', 'Обычный текст'), ('latex', 'Формула (LaTeX)'), ('point', 'Точка'), ('segment', 'Отрезок'), ('ray', 'Луч'), ('gline', 'Прямая'), ('vector', 'Вектор'), ('perp', 'Перпендикуляр'), ('parallel', 'Параллель'), ('perpbis', 'Серединный перпендикуляр'), ('bisector', 'Биссектриса'), ('circle', 'Окружность'), ('circ', 'Окружность по точкам'), ('conic', 'Коника по 5 точкам'), ('polygon', 'Многоугольник'), ('regpoly', 'Правильный многоугольник'), ('angle', 'Угол'), ('mark', 'Пометка (засечки, прямой угол)'), ('measure', 'Измерение'), ('frame', 'Математическое окно'), ('func', 'График функции'), ('implicit', 'Неявная кривая'), ('region', 'Область неравенства'), ('ftangent', 'Касательная'), ('farea', 'Площадь под графиком'), ('fintersect', 'Пересечение графиков'), ('image', 'Изображение'), ('pdf', 'Страница PDF'), ('geogebra', 'ГеоГебра'), ('embed', 'Встроенная страница'), ('poll', 'Голосование'), ('table', 'Таблица'), ('kanban', 'Канбан'), ('timer', 'Таймер'), ('wheel', 'Колесо'), ('slider', 'Ползунок-параметр'), ('sticky', 'Стикер'), ('card', 'Карточка'), ('boardconfig', 'Настройки доски (фон)')], max_length=24, verbose_name='Тип'),
        ),
    ]
