# Generated by Django 6.0.1 on 2026-08-20 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0010_alter_boardelement_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardhistory',
            name='element_type',
            field=models.CharField(blank=True, default='', max_length=24, verbose_name='Тип элемента'),
        ),
    ]
