# Generated by Django 6.0.1 on 2026-08-29 19:00
#
# Отметка «когда задан пароль». Она же служит пропуском, который лежит в
# сессии браузера: сменили пароль — отметка новая, все прежние пропуска
# перестали годиться сами собой.
#
# У досок, где пароль уже стоял до этой правки, отметки нет. Оставить её
# пустой нельзя: пропуск получился бы пустым, сравнение с ним никогда не
# сходилось бы, и такая доска не открылась бы даже по верному паролю.
# Поэтому проставляем время выполнения миграции — участникам придётся ввести
# пароль ещё один раз, и дальше всё пойдёт обычным чередом.

from django.db import migrations, models
from django.utils import timezone


def отметить_существующие(apps, schema_editor):
    Board = apps.get_model('board', 'Board')
    Board.objects.filter(password_enabled=True, password_set_at__isnull=True).update(
        password_set_at=timezone.now()
    )


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0014_alter_boardelement_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='password_set_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Пароль задан'),
        ),
        migrations.RunPython(отметить_существующие, migrations.RunPython.noop),
    ]
